<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MamuzBlogTest\Bootstrap'                             => __DIR__ . '/test/Bootstrap.php',
    'MamuzBlogTest\Controller\HashIdAdapterFactoryTest'   =>
    __DIR__ . '/test/MamuzBlogTest/Crypt/HashIdAdapterFactoryTest.php',
    'MamuzBlogTest\Controller\HashIdAdapterTest'          => __DIR__ . '/test/MamuzBlogTest/Crypt/HashIdAdaperTest.php',
    'MamuzBlogTest\Controller\QueryControllerFactoryTest' =>
    __DIR__ . '/test/MamuzBlogTest/Controller/QueryControllerFactoryTest.php',
    'MamuzBlogTest\Controller\QueryControllerTest'        =>
    __DIR__ . '/test/MamuzBlogTest/Controller/QueryControllerTest.php',
    'MamuzBlogTest\Entity\PostTest'                       => __DIR__ . '/test/MamuzBlogTest/Entity/PostTest.php',
    'MamuzBlogTest\Entity\TagTest'                        => __DIR__ . '/test/MamuzBlogTest/Entity/TagTest.php',
    'MamuzBlogTest\Mapper\Db\QueryTest'                   => __DIR__ . '/test/MamuzBlogTest/Mapper/Db/QueryTest.php',
    'MamuzBlogTest\Options\ConstraintTest'                => __DIR__ . '/test/MamuzBlogTest/Options/ConstraintTest.php',
    'MamuzBlogTest\Options\RangeTest'                     => __DIR__ . '/test/MamuzBlogTest/Options/RangeTest.php',
    'MamuzBlogTest\Service\FactoryTest'                   =>
    __DIR__ . '/test/MamuzBlogTest/DomainManager/FactoryTest.php',
    'MamuzBlogTest\Service\QueryFactoryTest'              =>
    __DIR__ . '/test/MamuzBlogTest/Service/QueryFactoryTest.php',
    'MamuzBlogTest\Service\QueryTest'                     => __DIR__ . '/test/MamuzBlogTest/Service/QueryTest.php',
    'MamuzBlogTest\View\Helper\HashIdFactoryTest'         =>
    __DIR__ . '/test/MamuzBlogTest/View/Helper/HashIdFactoryTest.php',
    'MamuzBlogTest\View\Helper\HashIdTest'                => __DIR__ . '/test/MamuzBlogTest/View/Helper/HashIdTest.php',
    'MamuzBlogTest\View\Helper\PagerFactoryTest'          =>
    __DIR__ . '/test/MamuzBlogTest/View/Helper/PagerFactoryTest.php',
    'MamuzBlogTest\View\Helper\PagerTest'                 => __DIR__ . '/test/MamuzBlogTest/View/Helper/PagerTest.php',
    'MamuzBlogTest\View\Helper\PostPanelTest'             =>
    __DIR__ . '/test/MamuzBlogTest/View/Helper/PostPanelTest.php',
    'MamuzBlog\Controller\QueryController'                => __DIR__ . '/src/MamuzBlog/Controller/QueryController.php',
    'MamuzBlog\Controller\QueryControllerFactory'         =>
    __DIR__ . '/src/MamuzBlog/Controller/QueryControllerFactory.php',
    'MamuzBlog\Crypt\AdapterInterface'                    => __DIR__ . '/src/MamuzBlog/Crypt/AdapterInterface.php',
    'MamuzBlog\Crypt\HashIdAdapter'                       => __DIR__ . '/src/MamuzBlog/Crypt/HashIdAdapter.php',
    'MamuzBlog\Crypt\HashIdAdapterFactory'                => __DIR__ . '/src/MamuzBlog/Crypt/HashIdAdapterFactory.php',
    'MamuzBlog\DomainManager\Factory'                     => __DIR__ . '/src/MamuzBlog/DomainManager/Factory.php',
    'MamuzBlog\DomainManager\ProviderInterface'           =>
    __DIR__ . '/src/MamuzBlog/DomainManager/ProviderInterface.php',
    'MamuzBlog\Entity\Post'                               => __DIR__ . '/src/MamuzBlog/Entity/Post.php',
    'MamuzBlog\Entity\Tag'                                => __DIR__ . '/src/MamuzBlog/Entity/Tag.php',
    'MamuzBlog\Feature\QueryInterface'                    => __DIR__ . '/src/MamuzBlog/Feature/QueryInterface.php',
    'MamuzBlog\Mapper\Db\Query'                           => __DIR__ . '/src/MamuzBlog/Mapper/Db/Query.php',
    'MamuzBlog\Module'                                    => __DIR__ . '/Module.php',
    'MamuzBlog\Options\Constraint'                        => __DIR__ . '/src/MamuzBlog/Options/Constraint.php',
    'MamuzBlog\Options\ConstraintInterface'               => __DIR__ . '/src/MamuzBlog/Options/ConstraintInterface.php',
    'MamuzBlog\Options\Range'                             => __DIR__ . '/src/MamuzBlog/Options/Range.php',
    'MamuzBlog\Options\RangeInterface'                    => __DIR__ . '/src/MamuzBlog/Options/RangeInterface.php',
    'MamuzBlog\Service\Query'                             => __DIR__ . '/src/MamuzBlog/Service/Query.php',
    'MamuzBlog\Service\QueryFactory'                      => __DIR__ . '/src/MamuzBlog/Service/QueryFactory.php',
    'MamuzBlog\View\Helper\HashId'                        => __DIR__ . '/src/MamuzBlog/View/Helper/HashId.php',
    'MamuzBlog\View\Helper\HashIdFactory'                 => __DIR__ . '/src/MamuzBlog/View/Helper/HashIdFactory.php',
    'MamuzBlog\View\Helper\Pager'                         => __DIR__ . '/src/MamuzBlog/View/Helper/Pager.php',
    'MamuzBlog\View\Helper\PagerFactory'                  => __DIR__ . '/src/MamuzBlog/View/Helper/PagerFactory.php',
    'MamuzBlog\View\Helper\PostPanel'                     => __DIR__ . '/src/MamuzBlog/View/Helper/PostPanel.php',
);
