<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'mamuz-blog/post-query/published-posts' => __DIR__ . '/view/mamuz-blog/post-query/published-posts.phtml',
    'mamuz-blog/post-query/published-post'  => __DIR__ . '/view/mamuz-blog/post-query/published-post.phtml',
    'mamuz-blog/tag-query/list'             => __DIR__ . '/view/mamuz-blog/tag-query/list.phtml',
    'mamuz-blog/tag-query/items'            => __DIR__ . '/view/mamuz-blog/tag-query/items.phtml',
);
