<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'mamuz-blog/post-query/active-posts' => __DIR__ . '/view/mamuz-blog/post-query/active-posts.phtml',
    'mamuz-blog/post-query/active-post'  => __DIR__ . '/view/mamuz-blog/post-query/active-post.phtml',
);
